### ISSUE TITLE
[QUESTION] Is 2d Scrolling avaliable for inifnity child nodes?

### ISSUE THREAD

**Issue by arcas0803** [gpmndev/recursive_tree_flutter#6]
Just a question to evaluate the use of the package.

Amazing work by the way.

**Comment by nvbien2000** [comment]
Hi, I'm sorry for this missing information. Let me check.

> Just a question to evaluate the use of the package.
> 
> Amazing work by the way.

**Comment by nvbien2000** [comment]
@arcas0803 Hi buddy, I still don't find anyway to apply multiple scroll for now. I guess I would create another personal repository becuz this library belongs to my current company.
