### ISSUE TITLE
Hello, could you please increase the multi-line display of the title of the configuration tree?

### ISSUE THREAD

**Issue by Duanyinyin504** [gpmndev/recursive_tree_flutter#7]
I have too many levels, and the sub-level titles inside cannot be displayed completely. I am using ‘ExpandableTreeWidget’, and the title can only display one line at most. Can you add multiple lines of configuration? I look forward to your reply.

**Comment by nvbien2000** [comment]
> I have too many levels, and the sub-level titles inside cannot be displayed completely. I am using ‘ExpandableTreeWidget’, and the title can only display one line at most. Can you add multiple lines of configuration? I look forward to your reply.

Sure lemme see

**Comment by gpmndev** [comment]
@Duanyinyin504 hi my fen, I just create ver 0.0.7 with `maxLines` property. I'm still new to GitHub open-source management, therefor I forget to create a branch for this issue 😄

**Comment by Duanyinyin504** [comment]
> @Duanyinyin504嗨，我的芬，我是@nvbien2000& 我只是用`maxLines`属性创建了 0.0.7 版。我对 GitHub 开源管理还是个新手，所以我忘记为这个问题创建一个分支 😄

Okay, thank you very much for your support, you have been a big help
