### ISSUE TITLE
Check or remove the check node to listen for changes

### ISSUE THREAD

**Issue by Duanyinyin504** [gpmndev/recursive_tree_flutter#9]
I am using ‘ExpandableTreeWidget’ and need to obtain in time whether any nodes are currently checked or removed. Can ‘onNodeDataChanged’ support be provided externally?Looking forward to your answer。

**Comment by nvbien2000** [comment]
Can you describe more? `AbsNodeType` already has `bool? isChosen` property, if this is what you mean.

**Comment by Duanyinyin504** [comment]
> 您能描述更多吗？`AbsNodeType`已经拥有`bool? isChosen`财产了，如果这就是你的意思的话。

I need to listen to the event that any node is checked. For example, after clicking a node, I need to know that the tree has changed.

**Comment by nvbien2000** [comment]
Seems like, there is no solution. You can Ctrl+C Ctrl+V file `expandable_tree_widget.dart` and customize it as your purpose.

![image](https://github.com/gpmndev/recursive_tree_flutter/assets/66837323/c6847338-3060-419e-9bc1-7e14ee4df46c)

**Comment by Duanyinyin504** [comment]
Okay, excuse me, thank you for your reply. In fact, I just want to pass 'onNodeDataChanged' to the outside of 'ExpandableTreeWidget'. It seems that I have to customize it.
